/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as BadgesIndexImport } from './routes/badges.index'
import { Route as BadgesIdImport } from './routes/badges.$id'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BadgesIndexRoute = BadgesIndexImport.update({
  id: '/badges/',
  path: '/badges/',
  getParentRoute: () => rootRoute,
} as any)

const BadgesIdRoute = BadgesIdImport.update({
  id: '/badges/$id',
  path: '/badges/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/badges/$id': {
      id: '/badges/$id'
      path: '/badges/$id'
      fullPath: '/badges/$id'
      preLoaderRoute: typeof BadgesIdImport
      parentRoute: typeof rootRoute
    }
    '/badges/': {
      id: '/badges/'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/badges/$id': typeof BadgesIdRoute
  '/badges': typeof BadgesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/badges/$id': typeof BadgesIdRoute
  '/badges': typeof BadgesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/badges/$id': typeof BadgesIdRoute
  '/badges/': typeof BadgesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/badges/$id' | '/badges'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/badges/$id' | '/badges'
  id: '__root__' | '/' | '/about' | '/badges/$id' | '/badges/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BadgesIdRoute: typeof BadgesIdRoute
  BadgesIndexRoute: typeof BadgesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BadgesIdRoute: BadgesIdRoute,
  BadgesIndexRoute: BadgesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/badges/$id",
        "/badges/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/badges/$id": {
      "filePath": "badges.$id.tsx"
    },
    "/badges/": {
      "filePath": "badges.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
