name: Build

on:
    push:
        branches:
            - main

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Publish
              uses: elgohr/Publish-Docker-Github-Action@main
              with:
                  name: shish2k/badger
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

    deploy:
        name: Deploy
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        needs:
            - publish
        steps:
            - name: Deploy
              uses: shish/watchtower-update@main
              with:
                  url: https://watchtower.shish.io/v1/update
                  api_token: ${{ secrets.WATCHTOWER_TOKEN }}
                  images: shish2k/badger
